### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by spikenheimer** [official-sounding/statparse#1]
i'm trying to run this utility and having issues :
 - trying to build the jar w `gradle shadowJar` and getting: 

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/spike/src/statparse-master/build.gradle' line: 37
> 
> * What went wrong:
> A problem occurred evaluating root project 'StatParse'.
> > org.gradle.api.internal.java.JavaLibrary.<init>(Lorg/gradle/api/artifacts/PublishArtifact;Lorg/gradle/api/artifacts/DependencySet;)V
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 

any help would be appreciated.

**Comment by official-sounding** [comment]
This should be fixed with the latest checkin -- looks like gradle 5.x does not like the old version of the shadow plugin used in the build file.
